### PR TITLE
Reorganize project

### LINKED ISSUE #2: Write docs
How the hell do _I_ use this thing, anyway?

### PR DESCRIPTION
**Pull request by segiddins**
Closes #2.

### CODE REVIEW

**Comment by segiddins** [comment]
@indirect please verify those docs are sufficient for you?

**Comment by segiddins** [comment]
@indirect please r?

**Comment by indirect** [comment]
This looks great to me.

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
